diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:pk>/', views.detail, name='detail'),
  path('new/', views.new, name='new'),
  path('create/', views.create, name='create'),
  path('<int:pk>/edit/', views.edit, name='edit'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

my_record/urls.py
from django.contrib import admin
from django.urls import include, path
from my_record import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', include('users.urls')),
    path('timer/', include('timer.urls')),
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include(('markdownx.urls','markdownx'))),
]

diary/models.py
from django.db import models
from markdownx.models import MarkdownxField
from users.models import User

class Diary(models.Model):
  title = models.CharField(verbose_name='タイトル', max_length=255, null=False, blank=False)
  body = MarkdownxField(verbose_name='本文', help_text="Markdown形式で本文を書こう", null=False, blank=False)
  user = models.ForeignKey(User, verbose_name='執筆者', on_delete=models.CASCADE)
  created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True, null=False)
  updated_at = models.DateTimeField(verbose_name='更新日', auto_now=True, null=False)

  def __str__(self):
    return self.title

diary/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField
from markdownx.widgets import MarkdownxWidget
from .models import Diary

class DiaryForm(forms.ModelForm):

  class Meta:
    model = Diary
    body = MarkdownxFormField()
    fields = ('title', 'body')

diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Diary
from .forms import DiaryForm

@login_required
def index(request):
  year = request.GET.get("year")
  month = request.GET.get("month")
  if year and month:
    if year.isdigit() and month.isdigit():
      diaries = Diary.objects.filter(user_id=request.user.id, updated_at__year=year, updated_at__month=month).order_by("-updated_at")
    else:
      diaries = []
  else:
    now = timezone.datetime.now()
    diaries = Diary.objects.filter(user_id=request.user.id, updated_at__month=now.month).order_by("-updated_at")
  filter_diaries = Diary.objects.filter(user_id=request.user.id)
  dates = filter_diaries.dates('updated_at', 'month', order='DESC')
  return render(request, 'diary/index.html', {'diaries': diaries, 'dates': dates})

@login_required
def detail(request, pk):
  diary = get_object_or_404(Diary, pk=pk)
  return render(request, 'diary/detail.html', {'diary': diary})

@login_required
def new(request):
  form = DiaryForm()
  return render(request, 'diary/new.html', {'form': form})

@login_required
def create(request):
  if request.method == "POST":
    form = DiaryForm(request.POST)
    if form.is_valid():
      diary = form.save(commit=False)
      diary.user_id = request.user.id
      diary.save()
      return redirect('diary:detail', pk=diary.id)
  else:
    form = DiaryForm()
  return render(request, 'diary/new.html', {'form': form})

@login_required
def edit(request, pk):
  diary = get_object_or_404(Diary, pk=pk)
  form = DiaryForm(instance=diary)
  return render(request, 'diary/edit.html', {'diary': diary, 'form': form})

@login_required
def update(request, pk):
  diary = Diary.objects.get(user_id=request.user.id, pk=pk)
  if request.method == "POST":
    form = DiaryForm(request.POST, instance=diary)
    if form.is_valid():
      update_diary = form.save(commit=False)
      update_diary.save()
      return redirect('diary:detail', pk=diary.id)
  else:
    form = DiaryForm(instance=diary)
  return render(request, 'diary/edit.html', {'diary': diary, 'form': form})

@login_required
def delete(request, pk):
  diary = Diary.objects.get(user_id=request.user.id, pk=pk)
  diary.delete()
  return redirect('diary:index')

diary/templates/diary/detail.html
{% extends "base.html" %}
{% load diary_conversion %}
{% block content %}
  <div class="container bg-white p-3">
    <div class="diary-header mb-5">
      <h1><strong>{{ diary.title }}</strong></h1>
      <p>
        <span class="mr-3">執筆者: {{ diary.user }}</span>
        <span>最終更新日: {{ diary.updated_at }}</span>
      </p>
    </div>
    {% display_body_markdown diary.body %}
  </div>
{% endblock %}

diary/templates/diary/edit.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'diary/css/style.css' %}" type="text/css">
{% endblock %}
{% block content %}
  <div class="container-field m-3">
    <form action="{% url 'diary:update' diary.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.title class="form-control form-control-lg" placeholder="タイトル" %}
      </div>
      <div class="form-group">
        {% render_field form.body class="form-control" placeholder="Markdown形式で本文を書こう" %}
      </div>
      {{ form.media }}
      <div class="text-right">
        <button type="submit" class="btn btn-primary">更新</button>
      </div>
    </form>
  </div>
{% endblock %}

diary/templates/diary/index.html
{% extends "base.html" %}
{% load static %}
{% block javascript_file %}
<script src="{% static 'diary/js/diary.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
  <div class="container bg-white">
    <a href="{% url 'diary:new' %}" class="btn btn-success mt-3 mb-3">新規作成</a>

    <div class="w-50 mb-3">
      <select name="date-filter" id="date-filter" class="form-control">
        <option value="">年月フィルター</option>
        {% for date in dates %}
          <option value="{{ date.year }}年{{ date.month }}月">{{ date.year }}年{{ date.month }}月</option>
        {% endfor %}
      </select>
    </div>

    {% if diaries %}
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">タイトル</th>
            <th scope="col" colspan="2">各種ボタン</th>
          </tr>
        </thead>
        <tbody>
          {% for diary in diaries %}
            <form action="{% url 'diary:delete' diary.id %}">
              <tr>
                <td><a href="{% url 'diary:detail' diary.id %}">{{ diary.title }}</a></td>
                <td><a href="{% url 'diary:edit' diary.id %}" class="btn btn-success">編集</a></td>
                <td><button type="submit" class="btn btn-danger">削除</button></td>
              </tr>
            </form>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>お探しの日記が見つかりませんでした</p>
    {% endif %}
  </div>
{% endblock %}

diary/templates/diary/new.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'diary/css/style.css' %}" type="text/css">
{% endblock %}
{% block content %}
  <div class="container-field m-3">
    <form action="{% url 'diary:create' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.title class="form-control form-control-lg" placeholder="タイトル" %}
      </div>
      <div class="form-group">
        {% render_field form.body class="form-control" placeholder="Markdown形式で本文を書こう" %}
      </div>
      {{ form.media }}
      <div class="text-right">
        <button type="submit" class="btn btn-primary">保存</button>
      </div>
    </form>
  </div>
{% endblock %}