diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:pk>/', views.detail, name='detail'),
  path('new/', views.new, name='new'),
  path('create/', views.create, name='create'),
  path('<int:pk>/edit/', views.edit, name='edit'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

my_record/urls.py
from django.contrib import admin
from django.urls import include, path
from my_record import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', include('users.urls')),
    path('timer/', include('timer.urls')),
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include(('markdownx.urls','markdownx'))),
]

timer/urls.py
from django.urls import path
from . import views

app_name = 'timer'
urlpatterns = [
  path('', views.index, name='index'),
  path('detail/', views.detail, name='detail'),
  path('create/', views.create, name='create'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('history/', views.history, name='history'),
  path('history/graph/', views.get_svg, name='graph')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
  path('login/', views.Login.as_view(), name='login'),
  path('logout/', views.Logout.as_view(), name='logout'),
  path('signup/', views.SignUp.as_view(), name='signup'),
]

templates/base.html
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Record</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    {% block css_file %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/base.js' %}" type="text/javascript"></script>
    {% block javascript_file %}
    {% endblock %}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-dark bg-header">
        <h1 class="title">
          <a href="/" class="text-light">My Record</a>
        </h1>
        <ul class="nav" id="global-nav">
          {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'timer:index' %}" class="nav-link text-light">タイマー</a></li>
            <li class="nav-item"><a href="{% url 'timer:history' %}" class="nav-link text-light">履歴</a></li>
            <li class="nav-item"><a href="{% url 'diary:index' %}" class="nav-link text-light">日記</a></li>
            <li class="nav-item">
              <form action="{% url 'users:logout' %}" method="POST" name='logout' class="logout-form">
                {% csrf_token %}
                <a href="javascript:logout.submit()" class="nav-link text-light">ログアウト</a>
              </form>
            </li>
          {% else %}
            <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link text-light">ログイン</a></li>
            <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link text-light">会員登録</a></li>
          {% endif %}
        </ul>

        <div id="side-menu">
          <div id="side-icon"><span></span><span></span><span></span></div>
          <div id="side-close"></div>
          <div id="side-content">
            <h2 class="side-title text-light">メニュー</h2>
            <ul class="nav flex-column">
              {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'timer:index' %}" class="nav-link">タイマー</a></li>
                <li class="nav-item"><a href="{% url 'timer:history' %}" class="nav-link">履歴</a></li>
                <li class="nav-item"><a href="{% url 'diary:index' %}" class="nav-link">日記</a></li>
                <li class="nav-item">
                  <form action="{% url 'users:logout' %}" method="POST" name='sidemenulogout' class="logout-form">
                    {% csrf_token %}
                    <a href="javascript:sidemenulogout.submit()" class="nav-link">ログアウト</a>
                  </form>
                </li>
              {% else %}
                <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link">ログイン</a></li>
                <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link">会員登録</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="bg-container pt-3 pb-3">
      {% block content %}
      {% endblock %}
    </div>

    <footer>
      <ul class="nav justify-content-center">
        {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'timer:index' %}" class="nav-link text-light">タイマー</a></li>
          <li class="nav-item"><a href="{% url 'timer:history' %}" class="nav-link text-light">履歴</a></li>
          <li class="nav-item"><a href="{% url 'diary:index' %}" class="nav-link text-light">日記</a></li>
        {% else %}
          <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link text-light">ログイン</a></li>
          <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link text-light">会員登録</a></li>
        {% endif %}
      </ul>
      <p class="text-center">©︎ 2020 daichan</p>
    </footer>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
{% endblock %}
{% block content %}
  <div class="container">
    <div class="text-center">
      <div class="content-title">
        <h1>「過去の自分と比較する」</h1>
        <p>
          日々の行動を記録し、振り返ることが成長へ近道<br>
          仕事や趣味、日常生活の変化を視覚化して楽しもう
        </p>
      </div>
  
      <div class="content-sub-title">
        <h2><span class="under-line">できること</span></h2>
      </div>

      <div class="row">
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">タイマー</h3>
              <p class="card-text">
                日々の色んな作業にどれくらい時間がかかるのかを計測できます。
                昨日の自分より早く作業ができるとちょっと嬉しいかも
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">行動履歴</h3>
              <p class="card-text">
                タイマーで記録した作業時間をグラフで視覚化します。
                昨日よりちょっと頑張れる自分になろう！
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">日記</h3>
              <p class="card-text">
                今日の出来事を記録できます。
                過去の自分の日記が今の自分にヒントをくれるかも！？
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}