diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:pk>/', views.detail, name='detail'),
  path('new/', views.new, name='new'),
  path('create/', views.create, name='create'),
  path('<int:pk>/edit/', views.edit, name='edit'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

my_record/urls.py
from django.contrib import admin
from django.urls import include, path
from my_record import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', include('users.urls')),
    path('timer/', include('timer.urls')),
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include(('markdownx.urls','markdownx'))),
]

timer/urls.py
from django.urls import path
from . import views

app_name = 'timer'
urlpatterns = [
  path('', views.index, name='index'),
  path('detail/', views.detail, name='detail'),
  path('create/', views.create, name='create'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('history/', views.history, name='history'),
  path('history/graph/', views.get_svg, name='graph')
]

timer/models.py
from django.db import models
from users.models import User
import math

class Timer(models.Model):
  name = models.CharField(verbose_name='タスク名', max_length=255, null=False, blank=False)
  elapsed_time = models.IntegerField(verbose_name='経過時間', null=False, blank=False, default=0)
  user = models.ForeignKey(User, verbose_name='ユーザー名', on_delete=models.CASCADE)
  created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True, null=False)
  updated_at = models.DateTimeField(verbose_name='更新日', auto_now=True, null=False)

  def __str__(self):
    return self.name
  
  def conversion_hour_time(self):
    hour = round(self.elapsed_time / (60 * 60), 2)
    return hour

timer/forms.py
from django import forms
from .models import Timer

class TimerForm(forms.ModelForm):

  class Meta:
    model = Timer
    fields = ('name', 'elapsed_time')

timer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.http.response import JsonResponse 
from django.utils import timezone
from .models import Timer
from .forms import TimerForm
from .utils import HistoryGraph
import json

@login_required
def index(request):
  now = timezone.datetime.now()
  timers = Timer.objects.filter(
    user_id=request.user.id,
    created_at__year=now.year,
    created_at__month=now.month,
    created_at__day=now.day
  ).order_by("-updated_at")
  return render(request, "timer/index.html", {'timers': timers})

@login_required
def detail(request):
  params = request.GET
  timer = Timer.objects.filter(
    user_id=request.user.id,
    name=params["name"],
    created_at__year=params["year"],
    created_at__month=params["month"],
    created_at__day=params["day"]
  ).first()
  if timer:
    res = {'id': timer.id, 'name': timer.name, 'elapsed_time': timer.elapsed_time}
    return JsonResponse(res)
  else:
    res = {'name': params["name"], 'elapsed_time': 0}
    return JsonResponse(res)

@login_required
def create(request):
  if request.method == 'POST':
    form = TimerForm(request.POST)
    if form.is_valid():
      timer = form.save(commit=False)
      timer.user_id = request.user.id
      timer.save()
      res = {'name': timer.name, 'elapsed_time': timer.elapsed_time}
      return JsonResponse(res)
    else:
      res = {'error_message': '適切な入力値ではありません'}
      return JsonResponse(res)
  else:
    res = {'error_message': 'error'}
    return JsonResponse(res)

@login_required
def update(request, pk):
  timer = Timer.objects.get(user_id=request.user.id, pk=pk)
  if request.method == 'POST':
    form = TimerForm(request.POST, instance=timer)
    if form.is_valid():
      update_timer = form.save(commit=False)
      update_timer.save()
      res = {'name': timer.name, 'elapsed_time': timer.elapsed_time}
      return JsonResponse(res)
    else:
      res = {'error_message': '適切な入力値ではありません'}
      return JsonResponse(res)
  else:
    res = {'error_message': 'error'}
    return JsonResponse(res)

@login_required
def delete(request, pk):
  if request.method == 'POST':
    timer = Timer.objects.get(user_id=request.user.id, pk=pk)
    timer.delete()
    return redirect('timer:index')
  else:
    raise Http404

@login_required
def history(request):
  now = timezone.datetime.now()
  week = HistoryGraph.display_period_week(now)
  display_monday = week['monday'].strftime('%Y/%m/%d')
  display_sunday = week['sunday'].strftime('%Y/%m/%d')
  return render(request, 'timer/history.html', {'monday': display_monday, 'sunday': display_sunday})

@login_required
def get_svg(request):
  # 本当はURLリクエストで日付をするのは調査中
  now = timezone.datetime.now()
  week = HistoryGraph.display_period_week(now)
  start = timezone.make_aware(week['monday'])
  end = timezone.make_aware(week['sunday'])
  timers = Timer.objects.filter(user_id=request.user.id, created_at__range=(start, end))
  svg = HistoryGraph.create_graph(timers, start, end)
  response = HttpResponse(svg, content_type='image/svg+xml')
  return response

timer/templates/timer/history.html
{% extends "base.html" %}
{% load static %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'timer/css/history.css' %}" type="text/css">
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row history">
      <div class="col-sm-9">
        <img src="{% url 'timer:graph' %}" alt="グラフ" class="graph">
      </div>
      <div class="col-sm-3">
        <p>週別集計</p>
        <p>{{ monday }}~{{ sunday }}</p>
      </div>
    </div>
  </div>
{% endblock %}

timer/templates/timer/index.html
{% extends "base.html" %}
{% load static %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'timer/css/index.css' %}" type="text/css">
{% endblock %}
{% block javascript_file %}
<script src="{% static 'timer/js/timer.js' %}" type="text/javascript"></script>
{% endblock %}
{% load timer_conversion %}
{% block content %}
  <div class="container">
    <div class="timer">
      <div class="card">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-6">
              <input type="text" id="task-name" class="form-control">
            </div>
            <div class="col-3 text-center" id="time"></div>
            <div class="col-3 text-center" id="icon">
              <img src="{% static 'timer/image/start.png' %}" alt="タイマースタート画像" id="timer-start" class="timer-button">
              <img src="{% static 'timer/image/stop.png' %}" alt="タイマーストップ画像" id="timer-stop" class="timer-button">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="timer-list">
      <p>Today</p>
      {% if timers %}
        <div class="card">
          <ul class="list-group list-group-flush">
            {% for timer in timers %}
              <li class="list-group-item">
                <div class="row align-items-center">
                  <div class="col-6">
                    {{ timer.name }}
                  </div>
                  <div class="col-3 text-center text-large elapsed-time">
                    {% display_time_notation timer.elapsed_time %}
                  </div>
                  <form action="{% url 'timer:delete' timer.id %}" method="POST" class="form col-3 text-center">
                    {% csrf_token %}
                    <button class="btn btn-danger">削除</button>
                  </form>
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}